version: '3'
services:
  database:
    links:
      - mysqldb
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpachato
    ports:
      - 3306:3306
    networks:
      - spring-mysql

  spring-boot:
    image: onschebbi/springproject
    container_name: springapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/tpachato?autoReconnect=true&useSSL=false
    ports:
      - 8089:8089
    depends_on:
      - database
    networks:
      - spring-mysql
    restart: on-failure

networks:
  AppNet: