version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'devops'
      MYSQL_DATABASE: 'tpachato'
      MYSQL_USER: 'devops'
      MYSQL_PASSWORD: 'devops'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - springdb:/var/lib/mysql

  spring_app:
    image: onschebbi/springproject
    container_name: springapp
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpachato?useSSL=false",
              "spring.datasource.username" : "devops",
              "spring.datasource.password" : "devops",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true

volumes:
  springdb:

